### ISSUE TITLE
Bug: `(new URL(...)).searchParams.get(...) is null` when calling maptilersdk.geocoding.byId(...)

### ISSUE THREAD

**Issue by toniopelo** [maptiler/maptiler-client-js#26]
Everything is in the title.
This is because when [calling `byId()` function](https://github.com/maptiler/maptiler-client-js/blob/5c887ee48d6f41b8c0032f3cb61734ab12e90ce2/src/services/geocoding.ts#L382C16-L382C16), the `apiKey` is not set in the URL that is passed to the `callFetch` function. But [the `callFetch` function](https://github.com/maptiler/maptiler-client-js/blob/5c887ee48d6f41b8c0032f3cb61734ab12e90ce2/src/callFetch.ts#L11) requires the api key to be set already.

**Comment by jonathanlurie** [comment]
Hey @toniopelo , thanks for reporting this! I'll try to fix that quick!

**Comment by toniopelo** [comment]
@jonathanlurie Hi! I've already published a PR linked to this issue, you can see it mentioned just above your comment. It should fix the problem. You might want to do it another way but it's a very minimal PR you could merge without too much effort. :)
