### ISSUE TITLE
staticMaps does not render image

### ISSUE THREAD

**Issue by cacobala** [maptiler/maptiler-client-js#38]
Other services seem to work well, but staticMaps keeps returning a "Invalid Key" image.

![image](https://github.com/maptiler/maptiler-client-js/assets/1614764/77d3cd84-5c43-4a7b-8699-63d84e5a787a)

**Comment by bolollo** [comment]
Hi @cacobala , are you trying it from a free account?

The Static Maps API is not available for free accounts. To use it you have to have a pay account. https://www.maptiler.com/cloud/pricing/#allPlans
